apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest24-backend-prod
  namespace: default
  labels:
    app: contest24-backend
    environment: production
    version: latest
spec:
  replicas: 2 # 운영환경 로드밸런싱 및 무중단 배포
  selector:
    matchLabels:
      app: contest24-backend
      environment: production
  template:
    metadata:
      labels:
        app: contest24-backend
        environment: production
        version: latest
    spec:
      # 테스트 노드 고정 배포
      nodeSelector:
        kubernetes.io/hostname: "contest-24-node-2-w-d514"

      containers:
        - name: contest24-backend
          image: contest24-registry.kr.ncr.ntruss.com/contest24-backend:latest

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          # 환경별 Secret/ConfigMap 주입
          envFrom:
            - secretRef:
                name: contest24-secrets
            - configMapRef:
                name: contest24-config-prod     # 운영환경 전용 ConfigMap

          env:
            - name: SERVER_PORT
              value: "8080"
            - name: ENVIRONMENT
              value: "production"
          # 리소스 제한(운영환경 이므로 테스트 환경보다 더 높은 사양 설정)
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

      # 컨테이너 레지스트리 인증
      imagePullSecrets:
        - name: regcred

      # 재시작 정책
      restartPolicy: Always